### ISSUE TITLE
Possible problem with projection system?

### ISSUE THREAD

**Issue by KimVeraa** [EVS-GIS/Fluvial-Corridor-Toolbox-ArcGIS-Desktop#1]
Hello,
I have been trying to apply the tool (StreamNetwork and ValleyBottom) to a catchment in India. The tool runs normally, but the resulting files are empty (nothing in attribute table and nothing on display). I have tried to run the tool with the example dataset and that works perfectly fine.  The only difference I can see between the example DEM and mine is the projection system (mine is WGS84), and the example data is something local (French) which I cannot convert my catchment too. I did  notice that when converting the example data to WGS84 and then running the tool, it also gives an empty result. So that makes  me think the problem is in the projection system, but I can't see this anywhere in the code... Do you have any idea how to address this? 
Many thanks in advance!

**Comment by fluviotect** [comment]
I had a similar issue trying to use data in a State Plane CRS.  I converted
to UTM and it ran fine.

Will

**Comment by KimVeraa** [comment]
That’s a great tip; it works now! Thank you!
Kim

**Comment by evs-gis-admin** [comment]
Please convert your dataset in UTM and it will work fine.
